spring.datasource.url=${LIBDEMO_TEST_DATASOURCE_URL}
spring.datasource.username=postgres
spring.datasource.password=postgres
server.servlet.context.path=/api
app.system.is.debug.mode=true
spring.profiles.active=test
FLUENTD_HOST=fluentd.local
FLUENTD_PORT=34224
TESTCONTAINERS_DISABLED=true
