services:
  app:
    container_name: libdemo_app
    ports:
      - "8080:8080"
      - "9010:9010"
    image: eclipse-temurin:21-jdk
    user: "1000"
    volumes:
      - ./target/libdemo-1.0.jar:/app/app.jar:ro
    working_dir: /app
    entrypoint: [
      "java",
      "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9010",
      "-Djava.security.egd=file:/dev/urandom",
      "-Djava.awt.headless=true",
      "-Xmx1G",
      "-jar",
      "/app/app.jar"
    ]
    env_file:
      - .env
    depends_on:
      - postgres
      - logstash

  postgres:
    container_name: libdemo_postgres
    image: postgres:18.4
    shm_size: 1g
    command:
      - --max_connections=100
      - --max_parallel_workers=6
      - --max_worker_processes=12
#      - -c
#      - log_statement=all
    volumes:
      - libdemo_pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=libdemo
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"

  elasticsearch:
    container_name: libdemo_elasticsearch
    image: elasticsearch:9.3.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - libdemo_es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: libdemo_kibana
    image: kibana:9.3.1
    environment:
      ELASTICSEARCH_HOSTS: '["http://libdemo_elasticsearch:9200"]'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    container_name: libdemo_logstash
    image: logstash:9.3.1
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch

  redis:
    container_name: libdemo_redis
    image: redis:8.10.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  libdemo_pg_data:
    name: libdemo_pg_data
  libdemo_es_data:
    name: libdemo_es_data
