services:
  libdemo:
    container_name: app_libdemo
    ports:
      - "58080:${SERVER_PORT:-8080}"
      - "59010:9010"
    image: eclipse-temurin:21-jdk
    user: "1000"
    volumes:
#      - ./target/lib:/app/lib
      - ./api/target/api-1.0.jar:/app/api.jar
      - ./core/target/core-1.0.jar:/app/core.jar
      - /usr/share/fonts:/app/fonts:ro
    working_dir: /app
    entrypoint: [
      "java",
      "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9010",
      "-Djava.security.egd=file:/dev/urandom",
      "-Djava.awt.headless=true",
      "-Xmx1G",
      "-cp",
      "/app/*.jar",
      "-jar",
      "/app/core.jar"
#      "-Dloader.path=/app/lib",
#      "org.springframework.boot.loader.launch.PropertiesLauncher"
    ]
#    environment:
#      - APPLICATION_UID=$(uuid)
    env_file:
      - .env
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: fluentd.local
#        tag: tag.libdemo

