server:
  forward-headers-strategy: framework
  tomcat:
    accept-count: 1000
    threads:
      max: 1000
spring:
  application:
    name: libdemo
  jackson:
    deserialization:
      # https://www.houseoftalents.nl/integrationapplicationtalents/blog/making-spring-boot-applications-return-bad-request-jsonview-ignored-properties
      fail-on-unexpected-view-properties: true
    mapper:
      default-view-inclusion: false
  datasource:
    hikari:
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.url}?reWriteBatchedInserts=true
  flyway:
    create-schemas: true
    table: flyway_library_schema_history
    schemas:
      - public
      - library
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        query:
          in_clause_parameter_padding: true
        order_updates: true
        order_inserts: true
  main:
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.data.elasticsearch.autoconfigure.DataElasticsearchReactiveRepositoriesAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.DataRedisRepositoriesAutoConfiguration
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: "[%X{requestId:-no-request-id}] [%X{userId:-no-user-id}] %clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} \
               %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} \
               %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    tracer: trace
    ru:
      valkeru:
        libdemo: debug
    co:
      elastic:
        clients: trace
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  open-api:
    info:
      version: 0.0.1-alpha
      title: Babylon library
      license:
        name: MIT
        url: https://opensource.org/license/mit
  swagger-ui:
    filter: true
    syntax-highlight:
      theme: idea
    default-model-expand-depth: 50
  enable-hateoas: false
app:
  security:
    jwt:
      secret: uSfKFfguss9AMp7cswFvHEmR4KvqnvfxwE7Fkp4Xj34vof72khNN7cFE7PnWKcLy
      lifetime: 3600
      refresh-lifetime: 604800
  system:
    elasticsearch-enabled: false
management:
  health:
    elasticsearch:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: dev,pre-production,test
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: trace
