name: Tests
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests
        run: ./mvnw test
